kind: pipeline
name: default
workspace:
  base: /tmp
  path: "."
steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm install -g vuepress
      - vuepress build docs
    when:
      event: [ push, tag ]
  - name: docker
    image: docker
    commands:
      - docker build . -t kubemq/docs:latest
