kind: pipeline
name: default
workspace:
  base: /tmp
  path: "."
steps:
  - name: build
    image: node
    commands:
      - npm install
      - vuepress build docs
    when:
      event: [ push, tag ]